spring.application.name=PassManager 

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

server.port=${SERVER_PORT}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=false

logging.level.org.springframework.security=INFO
logging.level.root=INFO

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:99900000}
